version: '3'
services:
  web:
    build: .
    ports:
    - "6060:8080"
    depends_on:
    - db
  db:
    image: mysql:5.7
    command: mysqld --user=root
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: companies
      MYSQL_USER: user
      MYSQL_PASSWORD: password